# Generated by Django 5.1.5 on 2025-01-20 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_category_post_created_post_publish_post_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(blank=True, choices=[('Draft', 'draft'), ('Published', 'published')], default='draft', max_length=10, null=True),
        ),
    ]
